caselink/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^m2a$', views.m2a, name='m2a'),
    url(r'^a2m$', views.a2m, name='a2m'),
    url(r'^data$', views.data, name='data'),
    url(r'^control$', views.task_control, name='task_control'),

    #RESTful APIs
    url(r'^manual/$', views.WorkItemList.as_view(), name='workitem'),
    url(r'^manual/(?P<pk>[a-zA-Z0-9\-]+)/$', views.WorkItemDetail.as_view(), name='workitem_detail'),
    url(r'^manual/(?P<workitem>[a-zA-Z0-9\-\._]+)/link/$', views.WorkItemLinkageList.as_view(), name='workitem_link_list'),
    url(r'^manual/(?P<workitem>[a-zA-Z0-9\-\._]+)/link/(?P<pattern>[a-zA-Z0-9\-\.\ _]*)/$', views.WorkItemLinkageDetail.as_view(), name='workitem_link_detail'),

    url(r'^auto/$', views.AutoCaseList.as_view(), name='auto'),
    url(r'^auto/(?P<pk>[a-zA-Z0-9\-\._]+)/$', views.AutoCaseDetail.as_view(), name='auto_detail'),

    url(r'^autocase_failure/$', views.AutoCaseFailureList.as_view(), name='auto_failure_list'),
    url(r'^autocase_failure/(?P<pk>[a-zA-Z0-9\-\._]+)/$', views.AutoCaseFailureDetail.as_view(), name='auto_failure_detail'),

    url(r'^link/$', views.LinkageList.as_view(), name='link'),
    url(r'^link/(?P<pk>[a-zA-Z0-9\-\._]+)/$', views.LinkageDetail.as_view(), name='link_detail'),

    url(r'^bug/$', views.BugList.as_view(), name='bug'),
    url(r'^bug/(?P<pk>[a-zA-Z0-9\-\._]+)/$', views.BugDetail.as_view(), name='bug_detail'),
]

libvirt_dashboard/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from rest_framework import routers, serializers, viewsets

urlpatterns = [
    url(r'^caselink/', include('caselink.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

views/statistics.py
from datetime import datetime
from flask import Blueprint, Markup, render_template, request, jsonify
from model import db, Run, AutoResult, ManualResult, Run
from sqlalchemy.orm import load_only, joinedload
from collections import Counter

dashboard_statistics = Blueprint('dashboard_statistics', __name__)
CHUNCK_SIZE = 300


def parse_date(keyword):
    try:
        ret = datetime(*[int(num) for num in request.args.get(keyword).split('-')])
    except (AttributeError, TypeError, ValueError):
        ret = None
    return ret


@dashboard_statistics.route('/auto/', methods=['GET'])
@dashboard_statistics.route('/run/<string:test_run>/auto/', methods=['GET'])
def autocase_statistics(test_run=None):
    def parse_date(keyword):
        try:
            ret = datetime(*[int(num) for num in request.args.get(keyword).split('-')])
        except (AttributeError, TypeError, ValueError):
            ret = None
        return ret

    after = parse_date('after')
    before = parse_date('before')

    query = AutoResult.query

    if after or before or test_run:
        query = query.join(Run)

    if before:
        query = query.filter(Run.date < before)

    if after:
        query = query.filter(Run.date > after)

    if test_run:
        query = query.filter(Run.name == test_run)

    cases = query.options(load_only('output', 'failure', 'skip', 'case')).yield_per(CHUNCK_SIZE)

    ret = {}

    for result_instance in cases:
        statistics = ret.setdefault(result_instance.case, {
            'failed': 0,
            'passed': 0,
            'skipped': 0,
            'invalid': 0,
            'total': 0,
        })
        statistics['total'] += 1
        if result_instance.result is None:
            statistics['invalid'] += 1
        else:
            statistics[result_instance.result] += 1
    return jsonify(ret), 200


@dashboard_statistics.route('/auto/<string:case>', methods=['GET'])
def autocase_detail(case):
    cases = AutoResult.query.filter(AutoResult.case == case)\
            .options(joinedload('run'))\
            .yield_per(CHUNCK_SIZE)

    ret = {}

    for result_instance in cases:
        statistics = ret.setdefault(result_instance.case, {
            'failed': [],
            'passed': [],
            'skipped': [],
            'invalid': [],
            'total': 0,
        })
        statistics['total'] += 1
        if result_instance.result is None:
            statistics['invalid'].append(result_instance.run.as_dict())
        else:
            statistics[result_instance.result].append(result_instance.run.as_dict())
    return jsonify(ret), 200


@dashboard_statistics.route('/run/', methods=['GET'])
@dashboard_statistics.route('/run/<string:name>', methods=['GET'])
def testrun_statistics(name=None):
    after = parse_date('after')
    before = parse_date('before')

    try:
        limit = int(request.args.get('limit', None))
    except Exception:
        limit = None

    query = Run.query

    if name:
        query = query.filter(Run.name == name)

    if before:
        query = query.filter(Run.date < before)

    if after:
        query = query.filter(Run.date > after)

    runs = query.options(load_only('date', 'name')).yield_per(CHUNCK_SIZE)
    ret = {}

    for run in runs:
        ret.setdefault(run.name, [])
        if limit is not None and len(ret[run.name]) >= limit:
            continue
        statistics = {'date': run.date.isoformat()}
        statistics.update(run.get_statistics())
        ret[run.name].append(statistics)

    return jsonify(ret), 200


@dashboard_statistics.route('/run/last/', methods=['GET'])
@dashboard_statistics.route('/run/last/<int:limit>', methods=['GET'])
def testrun_lastest(limit=None):
    query = Run.query.order_by(Run.date.desc())

    if limit:
        query = query.limit(limit)

    runs = query.options(load_only('date', 'name', 'id')).yield_per(CHUNCK_SIZE)
    ret = []

    for run in runs:
        ret.append(run.as_dict(statistics=True))
        db.session.commit()

    return jsonify(ret), 200

app/templates/column_table.html
{% extends "index.html" %}
{% block title %} Libvirt Dashboard {% endblock %}
{% block content %}
<table class='table' id='column_table'>
    <thead>
        <tr>
            {% for col in column_names %}
            <th>{{ col }}</th>
            {% endfor %}
        </tr>
    </thead>
</table>
{% endblock %}
{% block footer %}
<script type="text/javascript" charset="utf-8">
    sharedParameters.set("ajaxURL", "{{ajax}}");
    sharedParameters.set("templateColumns", [
        {% for col in column_datas %}
        "{{ col }}",
        {% endfor %}
    ]);
</script>
<script src="{{ url_for('static', filename='dist/column_table.js') }}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

app/templates/index.html
<html>
    <head>
        <meta charset="utf-8"></meta>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></meta>
        <title>{% block title %} Libvirt Dashboard {% endblock %} </title>
        <script type="text/javascript" charset="utf8" src="{{ url_for('static', filename='dist/vendor.bundle.js') }}"></script>
        <script type="text/javascript" charset="utf8" src="{{ url_for('static', filename='dist/head.js') }}"></script>
        <script type="text/javascript" charset="utf8" src="{{ url_for('static', filename='dist/init.js') }}"></script>
        <script type="text/javascript" charset="utf-8">
            sharedParameters.set("polarionURL", "{{ config.POLARION_URL }}");
        </script>
        {% block extra_header %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/">Libvirt Dashboard</a>
                </div>
                <div id="navbar" class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="/">Index</a></li>
                        <li><a href="/job-trigger">Job Trigger</a></li>
                    </ul>
                </div>
            </div>
        </nav>

        <div class="container-fluid">
            {% block content %}
            <div class="container">
                <div class="panel panel-default">
                    <div class="panel-heading">Table</div>
                    <div class="panel-body">
                        <a type="button" class="btn btn-info" href="#">Button</a>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">API</div>
                    <div class="panel-body">
                        <a type="button" class="btn btn-info" href="#">Button</a>
                    </div>
                </div>
            </div>
            {% endblock %}
        </div>
        {% block footer %}
        {% endblock %}
    </body>
</html>

app/templates/job_trigger.html
{% extends "index.html" %}
{% block title %} Libvirt Dashboard - Trigger Job {% endblock %}
{% block content %}
<div id='job-trigger'>
    <job-trigger trigger-gate-url="{{trigger_gate_url}}" get-job-names-url="{{get_job_names_url}}">
    </job-trigger>
</div>
{% endblock %}
{% block footer %}
<script src="{{ url_for('static', filename='dist/job_trigger.js') }}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

app/templates/resolve_auto.html
{% extends "index.html" %}
{% block title %} Libvirt Dashboard - Autotest Results {% endblock %}
{% block content %}
<div id='autoresult-resolving'>
    <autoresult-table dt-ajax-url="{{ajax}}" run-id="{{run_id}}">
    </autoresult-table>
</div>
{% endblock %}
{% block footer %}
<script src="{{ url_for('static', filename='dist/resolve_auto.js') }}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

app/templates/resolve_manual.html
{% extends "index.html" %}
{% block title %} Libvirt Dashboard - Generated Manuals {% endblock %}
{% block content %}
<div id="manualresult-resolving">
    <manualresult-table dt-ajax-url="{{ajax}}" run-id="{{run_id}}">
    </manualresult-table>
</div>
{% endblock %}
{% block footer %}
<script src="{{ url_for('static', filename='dist/resolve_manual.js') }}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

app/templates/testrun_dashboard.html
{% extends "index.html" %}
{% block title %} Libvirt Dashboard - Generated Manuals {% endblock %}
{% block extra_header %}

<link rel="stylesheet" href="{{ url_for('static', filename='css/dashboard.css') }}"></link>
<meta charset="utf-8">

{% endblock %}
{% block content %}

<div class="d3">
<form>
    <select name="test_run" id="test_run" value="">
        <option value="">All</option>
    </select>
    <label> <input type="checkbox" name="showing" value="auto_passed" checked="checked"> Passed </label>
    <label> <input type="checkbox" name="showing" value="auto_failed" checked="checked"> Failed </label>
    <label> <input type="checkbox" name="showing" value="auto_skipped" checked="checked"> Skip </label>
</form>
</div>

{% endblock %}
{% block footer %}
<script type="text/javascript" charset="utf-8">
    sharedParameters.set("templateStatisticURL", "{{url_for('dashboard_statistics.testrun_statistics', limit=0)}}");
</script>
<script src="{{ url_for('static', filename='dist/testrun_dashboard.js') }}" type="text/javascript" charset="utf-8"></script>

{% endblock %}

app/templates/testrun_diff.html
{#TODO use url_for for all links #}
{% extends "index.html" %}
{% block title %} Libvirt Dashboard - Generated Manuals {% endblock %}
{% block content %}
<div id="testrun-diff" class="container">
    <div class="panel panel-default">
        <div class="panel-heading test-run-panel">Test Runs </div>
        <div v-for="testrun in testRuns" v-if="ready">
            <table class='table'>
                <tr>
                    <th v-for="col in testAttrs"> ${col} </th>
                    <th> different </th>
                </tr>
                <tr v-for="testcase in testrun">
                    <th v-for="col in testAttrs"> ${testcase[col]} </th>
                    <th> ${testcase.different} </th>
                </tr>
            </table>
        </div>
    </div>
</div>
{% endblock %}

{% block footer %}
<script src="{{ url_for('static', filename='dist/testrun_diff.js') }}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

app/templates/testrun_overview.html
{#TODO use url_for for all links #}
{% extends "index.html" %}
{% block title %} Libvirt Dashboard - Generated Manuals {% endblock %}
{% block content %}
{% set column_names = ['Test Run', 'Date', 'Polarion Submit Date', 'Submit Status', 'Auto', 'Manual', 'Tags', 'Task'] %}
<div id="testrun-overview" class="container">
    <div class="panel panel-default">
        <div class="panel-heading test-run-panel">Test Runs
            <a class="pull-right" href="/api/run/" title="JSON format">
                API
            </a>
            <a class="pull-right" href="/table/run/" style="padding-right: 10px;" title="View in more detailed table">
                Table
            </a>
            <a class="pull-right" href="#" style="padding-right: 10px;" v-on:click="showSearchPanel = !showSearchPanel">
                Advanced Search
            </a>
        </div>
        <div v-show="showSearchPanel" id="datatable-selector" class="panel-body">
            <div class="input-group">
                <input type="radio" id="filter-all" value="all" v-model="submitStatus">
                <label for="filter-all">All</label>
                <br>
                <input type="radio" id="filter-submitted" value="submitted" v-model="submitStatus">
                <label for="filter-submitted">Submitted</label>
                <br>
                <input type="radio" id="filter-notsubmitted" value="notsubmitted" v-model="submitStatus">
                <label for="filter-notsubmitted">Not Submitted</label>
                <br>
            </div>
            <div class="input-group">
                <div v-for="item in availTags" class="checkbox checkbox-inline">
                    <input type="checkbox" v-bind:id="item.name" v-bind:value="item.name" v-bind:title="item.desc || item.name" v-model="checkedTags">
                    <label v-bind:for="item.name">
                        ${ item.name }
                    </label>
                </div>
            </div>
            <br />
            <div class="input-group">
                <span class="input-group-addon">Contains Auto Test case:</span>
                <input type="text" class="form-control" placeholder="Case ID" v-model="containsAutocase">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" v-on:click="reloadTable">Search</button>
                </span>
            </div>
            <br />
            <div class="input-group">
                <span class="input-group-addon">Contains Manual Test case:</span>
                <input type="text" class="form-control" placeholder="Case ID" v-model="containsManualcase">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="button" v-on:click="reloadTable">Search</button>
                </span>
            </div>
        </div>
        <table class='table' id='column_table'>
            <thead>
                <tr>
                    {% for col in column_names %}
                    <th>{{ col }}</th>
                    {% endfor %}
                </tr>
            </thead>
        </table>
    </div>
</div>
{% endblock %}

{% block footer %}
<script type="text/x-templates" charset="utf-8" id="testrun-child-row">
    <div class="testrun-child row">
        <div class="btn-group col-md-4">
            <div class="dropdown dropdown-auto">
                <button class="btn btn-default dropdown-toggle" type="button" id="runDropDown" data-toggle="dropdown" aria-haspopup="true">
                    Auto Results
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="runDropDown">
                    <li><a class='dashboard-resolve' title='View Test Results and Resolve existing errors manually' v-bind:href="autoResolveUrl">View and resolve</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a class='dashboard-table' title='View in table' v-bind:href="autoTableUrl">Table</a></li>
                    <li><a href="#" class='dashboard-api' title='View in JSON' v-bind:href="autoApi">API</a></li>
                </ul>
            </div>
            <span class="label dashboard-info-auto" v-bind:class="{ 'label-danger': !!testRun.auto_failed, 'label-info': !testRun.auto_failed}">
            ${autoSummary}
            </span>
        </div>
        <div class="btn-group col-md-4">
            <div class="dropdown dropdown-manual">
                <button class="btn btn-default dropdown-toggle" type="button" id="runDropDown" data-toggle="dropdown" aria-haspopup="true">
                    Manual Results
                    <span class="caret"></span>
                </button>
                <ul class="dropdown-menu" aria-labelledby="runDropDown">
                    <li><a class='dashboard-resolve' title='View Test Results and Resolve existing errors manually' v-bind:href="manualResolveUrl">View and resolve</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#" class='dashboard-table' title='View in table' v-bind:href="manualTableUrl">Table</a></li>
                    <li><a href="#" class='dashboard-api' title='View in JSON' v-bind:href="manualApi">API</a></li>
                </ul>
            </div>
            <span class="label dashboard-info-manual" v-bind:class="{ 'label-danger': !!testRun.manual_error, 'label-info': !testRun.manual_error}">
            ${manualSummary}
            </span>
        </div>
        <div class="btn-group col-md-4">
            <a class="btn btn-success dashboard-submit" title="Submit generated manual test results to polarion, test result will be blocked from being submitted until all auto test error and manual test result errors have been resolved." v-on:click="submitTestRun" v-bind:class="{ disabled: !!testRun.submit_date }">
                Submit to Polarion
            </a>
            <a class="btn btn-success dashboard-jump" title="Jump to the Polarin page." v-bind:href="polarionUrl" v-bind:class="{ disabled: !testRun.submit_date }" >
                View on Polarion
            </a>
            <a class="btn btn-danger dashboard-delete" title="Delete this test run. (UNRECOVERABLE)" v-on:click="deleteTestRun">
                Delete
            </a>
        </div>
    </div>
</script>
<script type="text/javascript" charset="utf-8">
    sharedParameters.set('datatablesAPIURL', "{{ url_for('dt_api.test_run_list')}}");
</script>
<script src="{{ url_for('static', filename='dist/testrun_overview.js') }}" type="text/javascript" charset="utf-8"></script>
{% endblock %}